---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:

      # - name: Get OCP version for 4.13 stable
      #   import_role:
      #     name: sshnaidm.ocptest.get_ocp_image
      #   vars:
      #     get_ocp_image_tag: "{{ ocp_version_tag | default('4.13') }}"
      #     get_ocp_image_release: "{{ ocp_version_release | default('stable') }}"

      - name: Get OCP version for 4.12.40
        import_role:
          name: sshnaidm.ocptest.get_ocp_image
        vars:
          get_ocp_image_full_version: "{{ ocp_version_full_version | default('4.12.40') }}"
